name: build-lf-lookup-tables

on:
  push:
    branches: [ '\d+.x' ]
  pull_request:
    branches: [ '\d+.x' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_VERSION: 1.0.${{github.run_number}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
          
    - name: dotnet restore
      run: dotnet restore

    - name: dotnet build
      run: dotnet build --no-restore

    - name: dotnet test
      run: dotnet test --no-build --verbosity normal

    - name: dotnet publish self-contained win-x64
      run: dotnet publish ./LookupTables/LookupTables.csproj --no-restore -c Release --self-contained -r win-x64 /p:Version=${{BUILD_VERSION}}

    - name: dotnet publish self-contained linux-x64
      run: dotnet publish ./LookupTables/LookupTables.csproj --no-restore -c Release --self-contained -r linux-x64 /p:Version=${{BUILD_VERSION}}

    - name: Upload lookuptables-win-x64 self contained package
      uses: actions/upload-artifact@v4
      with:
        name: lookuptables-win-x64
        path: ${{ github.workspace }}/LookupTables/bin/Release/net8.0/win-x64/publish/

    - name: Upload lookuptables-linux-x64 self contained package
      uses: actions/upload-artifact@v4
      with:
        name: lookuptables-linux-x64
        path: ${{ github.workspace }}/LookupTables/bin/Release/net8.0/linux-x64/publish/

  